# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '禽病网' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # Pods for 禽病网
	pod 'AFNetworking'
	pod 'MJRefresh'
	pod 'MJExtension'
	pod 'DZNEmptyDataSet'
	pod 'MBProgressHUD'
	pod 'YYCategories'
end
